---
name: AvoidSuffocation
main: blugin\avoidsuffocation\AvoidSuffocation
version: 1.0.0
api: [3.0.0]
authors: ['Blugin-team', 'PresentKim']
description: Automatically avoiding suffocation to sideways!
...