---
name: AvoidSuffocation
main: blugin\avoidsuffocation\AvoidSuffocation
version: 0.0.1
api: [4.0.0]
authors: ['Blugin-team', 'PresentKim']
description: Automatically avoiding suffocation to sideways!
...